#:schema node_modules/wrangler/config-schema.json
name = "create-next-app"
main = ".open-next/worker.ts"

compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Use the new Workers + Assets to host the static frontend files
assets = { directory = ".open-next/assets", binding = "ASSETS" }
